name: News Poster - Manual Run
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry run mode (no actual posting)'
        required: false
        default: 'true'
        type: boolean
      force_run:
        description: 'Force run even if no new articles (for testing)'
        required: false
        default: 'false'
        type: boolean

jobs:
  post-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run news poster (Manual)
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GMAIL_IMAP_USER: ${{ secrets.GMAIL_IMAP_USER }}
        GMAIL_IMAP_PASS: ${{ secrets.GMAIL_IMAP_PASS }}
        DRY_RUN: ${{ inputs.dry_run }}
        FORCE_RUN: ${{ inputs.force_run }}
      run: |
        python -m src.app.main
